---
- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Add Jenkins APT repository key
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository to sources list
  ansible.builtin.apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Wait for Jenkins to start (using URL test)
  ansible.builtin.uri:
    url: "{{ jenkins_url }}/login"
    method: GET
    status_code: 200 # Checks specifically for a 200 OK status
    validate_certs: no # Set to no for testing, use 'yes' in production with TLS
  register: jenkins_status_check
  until: jenkins_status_check.status == 200
  retries: 60     # Number of times to retry (60 retries)
  delay: 5

- name: Get initial Jenkins Admin Password for plugin installation
  ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: initial_admin_password
  changed_when: false

# --- Plugin Installation ---
- name: Install required Jenkins plugins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url: "{{ jenkins_url }}"
    url_username: "{{ jenkins_user }}"
    url_password: "{{ initial_admin_password.stdout }}"
    timeout: 120
    state: present
  loop: "{{ jenkins_plugins }}"
  # NOTE: The password lookup is safe ONLY on the master for the first run.